# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDemographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('distribution', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respone', models.CharField(max_length=500)),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QTSurvey.Question')),
                ('subjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QTSurvey.Subject')),
                ('surveyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QTSurvey.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=60)),
                ('salt', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='ownerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QTSurvey.User'),
        ),
        migrations.AddField(
            model_name='subject',
            name='researcherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QTSurvey.User'),
        ),
        migrations.AddField(
            model_name='question',
            name='surveyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QTSurvey.Survey'),
        ),
        migrations.AddField(
            model_name='customdemographic',
            name='subjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QTSurvey.Subject'),
        ),
    ]
