# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QTSurvey', '0002_auto_20170112_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(max_length=32),
        ),
    ]
