# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QTSurvey', '0003_auto_20170112_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDemographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=11)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CompletedSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderPosition', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='surveyID',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='researcherID',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='questionID',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='subjectID',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='surveyID',
        ),
        migrations.RemoveField(
            model_name='customdemographic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='customdemographic',
            name='subjectID',
        ),
        migrations.RemoveField(
            model_name='customdemographic',
            name='title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='customdemographic',
            name='field',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customdemographic',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='QTSurvey.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customdemographic',
            name='value',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='RSFlag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
        migrations.AddField(
            model_name='surveyfield',
            name='surveyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QTSurvey.Survey'),
        ),
        migrations.AddField(
            model_name='surveyaccess',
            name='surveyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QTSurvey.Survey'),
        ),
        migrations.AddField(
            model_name='surveyaccess',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QTSurvey.User'),
        ),
        migrations.AddField(
            model_name='completedsurvey',
            name='surveyFieldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QTSurvey.SurveyField'),
        ),
        migrations.AddField(
            model_name='completedsurvey',
            name='surveyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QTSurvey.Survey'),
        ),
        migrations.AddField(
            model_name='completedsurvey',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QTSurvey.User'),
        ),
        migrations.AddField(
            model_name='basedemographic',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QTSurvey.User'),
        ),
    ]
