# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 17:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QTSurvey', '0005_auto_20170201_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basedemographic',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='basedemographic',
            name='id',
        ),
        migrations.RemoveField(
            model_name='basedemographic',
            name='lastName',
        ),
        migrations.AddField(
            model_name='basedemographic',
            name='demoId',
            field=models.IntegerField(default=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basedemographic',
            name='first_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='basedemographic',
            name='last_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='irbconsent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='basedemographic',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='basedemographic',
            name='phone',
            field=models.CharField(max_length=11, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='basedemographic',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
