# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QTSurvey', '0006_auto_20170221_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRBConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='irbconsent',
            new_name='consentneeded',
        ),
        migrations.AddField(
            model_name='irbconsent',
            name='surveyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QTSurvey.Survey'),
        ),
        migrations.AddField(
            model_name='irbconsent',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
